# fly.toml app configuration file generated for github-portfolio-showcase on 2026-01-01T18:00:00-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'reponexus-portfolio'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[env]
  NEXT_OUTPUT_MODE = "standalone"
  DATABASE_URL = "file:/data/sqlite.db"
  # PORT = "3000" # set in Dockerfile

[mounts]
  source = "sqlite_data"
  destination = "/data"

# The following secrets must be set using `fly secrets set`:
# NEXTAUTH_SECRET
# ENCRYPTION_KEY
# OPENROUTER_API_KEY
# GITHUB_CLIENT_ID
# GITHUB_CLIENT_SECRET
